----DATA WAREHOUSING PROJECT----

---ETL---
-- EXTRACT TRANSFORM LOAD ---

---MEDALLION ARCHTECTURE IT HAS THREE LAYERS 1.BRONZE 2.SILVER 3.GOLD

---1.BRONZE LAYE IT CONTAINS RAW DATA AND UNPROCCESED DAT FROM SOURCE FOR TRACEABILITY AND DEBUGGING
---2.SILVER LAYER IT CONTAINS CLEAN AND STANDARDIZED DATA FOR INTERMEDIATE LAYER PREPARE FOR DATA ANALYSIS
---3.GOLD LAYER IT CONTAINS BUSINESS READY DATA PROVIDE DATA TO BE CONSUMED FOR REPORTING AND ANALYTICS

---Create Database  'DataWarehouse'


use master;
GO

--Drop and recreate the 'DataWarehouse' database
IF EXISTS(SELECT 1 FROM sys.databses WHERE name = 'DataWarehouse')
BEGIN
  ALTER DATABASE DataWarehouse SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
  DROP DATABSE DataWarehouse;
END;
GO
CREATE DATABASE DataWarehouse;

use DataWarehouse;

CREATE SCHEMA bronze;
GO
CREATE SCHEMA silver;
GO
CREATE SCHEMA gold;
GO

